config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get '/about' => 'pages#about'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/register' => 'users#new'
  resources :users, only: [:show, :create]

  resources :schedules, only: [:new, :create, :edit, :update]

  resources :experiences, except: :destroy do
    resources :comments, only: [:create, :edit, :update]
  end

  resources :questions, except: :destroy do
    resources :comments, only: [:create, :edit, :update]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, presence: true

  belongs_to :user
  belongs_to :commentable, polymorphic: true
end

app/models/experience.rb
class Experience < ActiveRecord::Base
  belongs_to :user
  has_many :comments, -> { order(created_at: :desc) }, as: :commentable

  validates_presence_of :user, :title, :body
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :comments, -> { order(created_at: :desc) }, as: :commentable

  validates_presence_of :user, :question
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :user, :start_date, :daily_sleep_goal, :core_sleep, :nap_count, :nap_duration
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true

  has_secure_password
  validates :password, length: { minimum: 5 }

  has_one :schedule
  has_many :questions
  has_many :experiences
  has_many :comments

  delegate :start_date, :end_date, :daily_sleep_goal, :core_sleep, :nap_count, :nap_duration, to: :schedule
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    !!current_user
  end

  def is_logged_in
    redirect_to home_path if current_user
  end

  def require_user
    unless logged_in?
      store_location
      flash[:danger] = "You must be logged in to do that!"
      redirect_to login_path
    end
  end

  def access_denied
    flash[:danger] = "You aren't allowed to do that!"
    redirect_to root_path
  end

  def correct_user(obj)
    access_denied unless !obj.nil? && obj.user == current_user
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end

  def redirect_back_or(default)
    redirect_to session[:forwarding_url] || default
    session.delete(:forwarding_url)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user
  before_action :find_comment, only: [:edit, :update]
  before_action :load_commentable
  before_action -> { correct_user(@comment) }, only: [:edit, :update]

  def create
    @comment = @commentable.comments.new(comment_params.merge!(user: current_user))

    if @comment.save
      flash[:success] = "Your comment has been posted."
      redirect_to @commentable
    else
      render @comment.commentable_type.downcase + "s/show"
    end
  end

  def update
    if @comment.update(comment_params)
      flash[:success] = "Your comment has been updated."
      redirect_to @commentable
    else
      render :edit
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end

    def load_commentable
      resource, id = request.path.split('/')[1, 2]
      @commentable = resource.singularize.classify.constantize.find(id)
    end

    def find_comment
      @comment = current_user.comments.find_by(id: params[:id])
    end
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :require_user, except: [:index, :show]
  before_action :get_experience, only: [:edit, :update]
  before_action -> { correct_user(@experience) }, only: [:edit, :update]

  def index
    @experiences = Experience.all
  end

  def show
    @experience = Experience.find(params[:id])
    @comment = Comment.new
  end

  def new
    @experience = Experience.new
  end

  def create
    @experience = Experience.new(experience_params.merge!(user: current_user))

    if @experience.save
      flash[:success] = "Your experience has been posted."
      redirect_to @experience
    else
      render :new
    end
  end

  def update
    if @experience.update(experience_params)
      flash[:success] = "Your post has been update."
      redirect_to @experience
    else
      render :new
    end
  end

  private

    def experience_params
      params.require(:experience).permit(:title, :body)
    end

    def get_experience
      @experience = current_user.experiences.find_by(id: params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :require_user, except: [:index, :show]
  before_action :get_question, only: [:edit, :update]
  before_action -> { correct_user(@question) }, only: [:edit, :update]

  def index
    @questions = Question.all.order(:created_at).reverse_order
  end

  def show
    @question = Question.find(params[:id])
    @comment = Comment.new
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params.merge!(user: current_user))

    if @question.save
      flash[:success] = "Your question has been submitted."
      redirect_to questions_path
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      flash[:success] = "Your question has been updated."
      redirect_to questions_path
    else
      render :edit
    end
  end

  private

    def question_params
      params.require(:question).permit(:question, :additional_info)
    end

    def get_question
      @question = current_user.questions.find_by(id: params[:id])
    end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :require_user
  before_action :get_schedule, only: [:edit, :update]
  before_action -> { correct_user(@schedule) }, only: [:edit, :update]

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(schedule_params.merge!(user_id: current_user.id))

    if @schedule.save
      flash[:success] = "Your schedule has been created."
      redirect_to @schedule.user
    else
      render :new
    end
  end

  def update
    if @schedule.update(schedule_params)
      flash[:success] = "Your schedule has been updated."
      redirect_to @schedule.user
    else
      render :edit
    end
  end

  private

    def schedule_params
      params.require(:schedule).permit!
    end

    def get_schedule
      @schedule = current_user.schedule
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      log_in(user)
      flash[:success] = "You are now logged in."
      redirect_back_or user
    else
      flash.now[:danger] = "Incorrect username or password."
      render :new
    end
  end

  def destroy
    if logged_in?
      session[:user_id] = nil
      flash[:info] = "You have logged out."
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in(@user)
      flash[:success] = "Thanks for joining! Welcome and enjoy."
      redirect_to @user
    else
      render :new
    end
  end

  private

    def user_params
      params.require(:user).permit(:username, :phone_number, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.slim
-if comment.valid?
  section.area
    p= comment.content
    small
      = comment.user.username
      '  | Posted
      = time_ago_in_words(comment.created_at)
    -if logged_in? && comment.user == current_user
      small.pull-right
        = link_to [:edit, comment.commentable, comment] do
          i.glyphicon.glyphicon-edit>
          '  Edit

        
        

app/views/comments/_form.slim
-new_comment = @comment.new_record?

= render 'shared/errors', obj: @comment

#content-form
  h1= new_comment ? "New Comment" : "Edit Comment"
  = form_for [commentable, @comment] do |f|
    .input
      = f.text_area :content, class: "form-control"
    
    .input
      = f.submit new_comment ? "Create" : "Update", class: "btn btn-success"

app/views/comments/edit.slim
= render 'form', commentable: @commentable

app/views/experiences/_experience.slim
.container.area
  h4= link_to experience.title, experience
  p
    = experience.body
  small
    = experience.user.username
    '  | posted
    = time_ago_in_words(experience.created_at)
  -if logged_in? && experience.user == current_user
    small.pull-right
      = link_to edit_experience_path(experience) do
        i.glyphicon.glyphicon-edit>
        '  Edit

app/views/experiences/_form.slim
-new_experience = @experience.new_record?

= render 'shared/errors', obj: @experience

#content-form
  h2= new_experience ? "New Experience" : "Edit Experience"
  = form_for @experience do |f|
    .input
      = f.label :title
      .field
        = f.text_field :title
    
    .input
      = f.label :body
      .field
        = f.text_area :body, rows: 10
    
    .input
      = f.submit new_experience ? "Publish" : "Update", class: 'btn btn-primary'

app/views/experiences/edit.slim
= render 'form'

app/views/experiences/index.slim
-if logged_in?
  section
    #new-submission
      = link_to new_experience_path do
        i.glyphicon.glyphicon-plus>
        | Share your experiences as a Polyphasic sleeper!
section
  = render @experiences

app/views/experiences/show.slim
= render 'shared/user_content', obj: @experience
  

app/views/layouts/_messages.slim
- flash.each do |name, msg|
  .alert(class= "alert-#{name}")
    a.close data-dismiss="alert" x
    = content_tag :div, msg, id: "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_nav.slim
#header
  section
    #nav-toggle
      = image_tag "sheep.png", class: 'front'
      = image_tag "close.png", class: 'back'
    #site-menu
      h2= link_to "Home", root_path
      h2= link_to "Learn more", about_path
      h2= link_to "Experiences", experiences_path
      h2= link_to "Questions", questions_path
    .page-title
      h1 Everyman
    .user-ctrl
      -if logged_in?
        h3.dropdown
          .btn-dark.dropdown-toggle data-toggle="dropdown"
            = current_user.username
            span.caret<
          ul.dropdown-menu
            li= link_to user_path(current_user) do
              i.glyphicon.glyphicon-user>
              | Profile
            -if current_user.schedule == nil
              li= link_to new_schedule_path do
                i.glyphicon.glyphicon-calendar
                | Schedule
            -else
              li= link_to edit_schedule_path(current_user.schedule) do
                i.glyphicon.glyphicon-calendar
                | Schedule
            li= link_to logout_path, method: :delete do
              i.glyphicon.glyphicon-log-out>
              | Logout
      -else
        h3= link_to "Login", login_path, class: 'btn-dark'
    

          

app/views/layouts/application.slim
doctype html
html
  head
    title
      | Everyman
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    #site-wrapper
      #site-canvas
        =render 'layouts/nav'
        .container
          =render 'layouts/messages'
          = yield
    = yield :javascript

app/views/pages/about.slim
container
  .intro.area
    h2 Introduction
    p
      | Polyphasic sleep is the practice of sleeping multiple times in a 24 hour period. This can range anywhere from two sleep cycles,
        to multiple sessions divied up throughout the day. The term is believed to have been coined by psychologist  J. S. Szymanski. It is
        widely observed throught various animal groups, and is considered the ancestral sleep pattern of most mammals.
    p
      | Humans along with the other species belonging to the Homininae Subfamily are considered to be biphasic sleepers. In
        nature they are observed to have a major sleep cycle during the night, with a shorter mid day nap ranging between 1-3 hours. However
        in modern culture most people tend to chunk this pattern into one major sleep cycle. It's no coincidence most people
        expierence a "mid-day slump". In fact in many parts of the world this sleeping habit is still widely practiced, and is especially 
        prevalent in less developed areas that have less access to electricity and nightime lighting. In other other cultures it's a general
        practice to have a mid-day break. Businesses close, workers are able to go home for a meal and nap before returning to work a couple
        hours later.
    p 
      | Polyphasic sleep does not refer to any single sleep pattern, it's an umbrella term for anything other than a monophasic sleep 
        schedule. Recently there has been some development in extending this general pattern even further. It has been observed that as we
        splinter our sleep cycle into more evenly distributed chunks throughout the day we need less overal sleep. This is true even for 
        biphasic sleep patterns, on average an extra hour of wakefulness is observed, in contrast to an eight hour monophasic sleep pattern.
    
    p 
      | Going along this line several sleep patterns have been developed and documented. These sleep schedules aim to reduce the total amount
        of time spent sleeping, by limiting the amount we sleep during the night and having one or more naps throught the day. As anything in 
        the field of human study and especially in the little understood human psyche, this has led to some controversy. Critques claim it's
        an unsound theory and that over time these nappers will suffer the same effects of those with chronic sleep disorders, such as
        reduced mental and physical ability, increased strees and anxiety, and a weakened immune system.
    
    p
      | Knowing scientists and doctors, this could take decades to study or begin approaching as a scientific community. Meanwhile there is
        potentially valuable time being spent sleeping every night. As they say, "Time is money!".

    p
      | Anyone with a busy schedule or that seeks to increase productivity is certain to be interested. Thus I've decided to test this 
        theory, and invite you to join along. I've made this app to help me during this expirement and to possibly help others curious 
        as to whether they can really increase their total time awake. I'm making no claims as to whether this will work beforehand
        and as usual results may vary. I must also advise; 
      br
        | ATTEMPT AT YOUR OWN RISK.

app/views/pages/home.slim
.row.separator
  .catch
    h1 
      | It's your time.
      br
      | What'll you do with it?
    -if !logged_in?
      =link_to "Start today", register_path, class: 'btn-dark'
    =link_to "Learn more", about_path
  #carousel
    ul
      li= image_tag "study.jpg", class: 'img-responsive'
      li= image_tag "programming.jpg", class: 'img-responsive'
      li= image_tag "jogging.jpg", class: 'img-responsive'
      li= image_tag "photo.jpg", class: 'img-responsive'
- content_for :javascript do
  = javascript_include_tag 'carousel'

app/views/questions/_form.slim
-new_question = @question.new_record?

= render 'shared/errors', obj: @question

#content-form
  h1= new_question ? "New Question" : "Edit Question"
  = form_for @question do |f|
    .input
      = f.label :question
      .field
        = f.text_field :question
    
    .input
      = f.label :additional_info
      .field
        = f.text_area :additional_info, rows: 10
        
    .input
      = f.submit new_question ? "Create" : "Update", class: "btn btn-primary"

app/views/questions/_question.slim
.container.area
  h4= link_to question.question, question
  p
    = question.additional_info
  small
    = question.user.username
    '  | posted
    = time_ago_in_words(question.created_at)
  -if logged_in? && question.user == current_user
    small.pull-right
      = link_to edit_question_path(question) do
        i.glyphicon.glyphicon-edit>
        '  Edit

app/views/questions/edit.slim
= render 'shared/errors', obj: @question
= render 'form'

app/views/questions/index.slim
-if logged_in?
  section
    #new-submission
      = link_to new_question_path do
        i.glyphicon.glyphicon-question-sign>
        | Ask a question
        
section
  = render @questions

app/views/questions/new.slim
= render 'form'

app/views/questions/show.slim
= render 'shared/user_content', obj: @question

app/views/schedules/_form.slim
=render 'shared/errors', obj: @schedule
#user-form
  = form_for @schedule do |f|
    .input
      .input-group.date#start
        = f.label :start_date
        = f.text_field :start_date
        span.input-group-addon
          span.glyphicon.glyphicon-calendar
          
    .input
      .input-group.date#end
        = f.label :end_date
        = f.text_field :end_date
        span.input-group-addon
          span.glyphicon.glyphicon-calendar
    
    .input
      .input-group.date#daily
        = f.label :daily_sleep_goal, "Daily total"
        = f.text_field :daily_sleep_goal
        span.input-group-addon
          span.glyphicon.glyphicon-time
        
    .input
      .input-group.date#core
        = f.label :core_sleep
        = f.text_field :core_sleep
        span.input-group-addon
          span.glyphicon.glyphicon-time
        
    .input
      .input-group.date#nap-count
        = f.label :nap_count, "Total Naps"
        = f.text_field :nap_count
        span.input-group-addon
          span.glyphicon.glyphicon-dashboard
      
    .input
      .input-group.date#nap-duration
        = f.label :nap_duration
        = f.text_field :nap_duration
        span.input-group-addon
          span.glyphicon.glyphicon-time
    
    .input
      = f.submit "Save", class: "btn btn-primary"

- content_for :javascript do
  = javascript_include_tag 'schedule'

app/views/schedules/edit.slim
=render 'form'

app/views/schedules/new.slim
=render 'form'

app/views/shared/_errors.slim
- if obj.errors.any?
  .alert.alert-danger.text-center
    ' The Form contains
    = pluralize obj.errors.count, 'error'
    - obj.errors.full_messages.each do |msg|
      br
      = msg

app/views/shared/_user_content.slim
-obj ||= @comment.commentable
= render obj
-if logged_in?
  .container
    = render "comments/form", commentable: obj
.container
  h3.text-center= obj.comments.any? ? "Comments" : ""
  = render obj.comments

app/views/users/_form.slim
=render 'shared/errors', obj: @user
#user-form
  h1 Registration
  = form_for @user do |f|
    .input
      = f.label :username
      .field
        = f.text_field :username
        
    .input
      = f.label :password
      .field
        = f.password_field :password
        
    .input
      = f.label :password_confirmation, "Confirmation"
      .field
        = f.password_field :password_confirmation
    
    .input
      = f.submit "Create Profile", class: 'btn btn-success'
        

app/views/users/show.slim
.col-md-10.col-md-offset-1
  h3 
    ' Username:
    =@user.username.capitalize
  -if @user.schedule != nil
    h3 
      ' Schedule start date:
      =@user.start_date
    h3
      ' Schedule end date:
      =@user.end_date
    h3 
      ' Daily sleep goal:
      =@user.daily_sleep_goal
    h3 
      ' Core sleep:
      =@user.core_sleep
    h3 
      ' Naps:
      =@user.nap_count
    h3
      ' Nap duration:
      =@user.nap_duration